### ISSUE TITLE
not full screen

### ISSUE THREAD

**Issue by ghost** [eworm-de/mkinitcpio-archlogo#1]
I made an own ascii-art logo, but it isn't appear correctly. It only uses an about 80 column wide area of the screen.
My screen, and my own logo are 180 columns wide.

**Comment by eworm-de** [comment]
I suppose your lines have a break at 80 characters? That is because the `archlogo` unit/hook is started early in boot process when console actually has a width of 80 characters.

If you want a wider logo make sure it starts later in boot process.

For `systemd`-enabled `initcpio` remove the `Before=` line and make sure it starts after `udev` runs `systemd-vconsole-setup` (`udev` rule file `90-vconsole.rules`).

For legacy `initcpio` edit `hook/archlogo` and make it a late hook (replace `run_earlyhook` with `run_latehook`).

All this is untested, so good luck!

**Comment by ghost** [comment]
Replacing run_earlyhook with run_latehook solved the problem. Thank you.
